<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-UBCSR-20160203174442" Class="CSRContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-UBCSR-20160203174442.mdf;Initial Catalog=aspnet-UBCSR-20160203174442;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_UBCSR_20160203174442ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ItemCategory" Member="ItemCategories">
    <Type Name="ItemCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ItemCategory_Item" Member="Items" ThisKey="Id" OtherKey="ItemCategoryId" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.ItemBrand" Member="ItemBrands">
    <Type Name="ItemBrand">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ItemBrand_Item" Member="Items" ThisKey="Id" OtherKey="ItemBrandId" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemBrandId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Item_InventoryLINQ" Member="InventoryLINQs" ThisKey="Id" OtherKey="ItemId" Type="InventoryLINQ" />
      <Association Name="ItemBrand_Item" Member="ItemBrand" ThisKey="ItemBrandId" OtherKey="Id" Type="ItemBrand" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ItemCategory_Item" Member="ItemCategory" ThisKey="ItemCategoryId" OtherKey="Id" Type="ItemCategory" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Memberships" Member="MembershipLINQs">
    <Type Name="MembershipLINQ">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowsStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="User_MembershipLINQ" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_MembershipLINQ" Member="MembershipLINQ" ThisKey="UserId" OtherKey="UserId" Type="MembershipLINQ" Cardinality="One" />
      <Association Name="User_UsersInRole" Member="UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Role_UsersInRole" Member="UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.UsersInRoles" Member="UsersInRoles">
    <Type Name="UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UsersInRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UsersInRole" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExperimentNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateRequested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LabRoom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApprovalStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsReleased" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsReturned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReleasedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReturnedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DisapproveRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Reservation_ReservationItem" Member="ReservationItems" ThisKey="Id" OtherKey="ReservationId" Type="ReservationItem" />
      <Association Name="Reservation_Group" Member="GroupLINQs" ThisKey="Id" OtherKey="ReservationId" Type="GroupLINQ" />
      <Association Name="SubjectLINQ_Reservation" Member="SubjectLINQ" ThisKey="SubjectId" OtherKey="Id" Type="SubjectLINQ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="InventoryLINQs">
    <Type Name="InventoryLINQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stocks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Expiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="InventoryLINQ_ReservationItem" Member="ReservationItems" ThisKey="Id" OtherKey="InventoryId" Type="ReservationItem" />
      <Association Name="InventoryLINQ_GroupItem" Member="GroupItems" ThisKey="Id" OtherKey="InventoryId" Type="GroupItem" />
      <Association Name="Item_InventoryLINQ" Member="Item" ThisKey="ItemId" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="AccountLINQs">
    <Type Name="AccountLINQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationItem" Member="ReservationItems">
    <Type Name="ReservationItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InventoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReservationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityByGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="InventoryLINQ_ReservationItem" Member="InventoryLINQ" ThisKey="InventoryId" OtherKey="Id" Type="InventoryLINQ" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Reservation_ReservationItem" Member="Reservation" ThisKey="ReservationId" OtherKey="Id" Type="Reservation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="SubjectLINQs">
    <Type Name="SubjectLINQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="YearFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SubjectLINQ_Reservation" Member="Reservations" ThisKey="Id" OtherKey="SubjectId" Type="Reservation" />
      <Association Name="Section_SubjectLINQ" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Section" Member="Section1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Section_SubjectLINQ" Member="SubjectLINQs" ThisKey="Id" OtherKey="SectionId" Type="SubjectLINQ" />
    </Type>
  </Table>
  <Table Name="dbo.GroupMember" Member="GroupMembers">
    <Type Name="GroupMember">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Group_GroupMember" Member="GroupLINQ" ThisKey="GroupId" OtherKey="Id" Type="GroupLINQ" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.GroupItem" Member="GroupItems">
    <Type Name="GroupItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InventoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BorrowedQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Breakage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="HasBreakage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReturnedQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="InventoryLINQ_GroupItem" Member="InventoryLINQ" ThisKey="InventoryId" OtherKey="Id" Type="InventoryLINQ" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Group_GroupItem" Member="GroupLINQ" ThisKey="GroupId" OtherKey="Id" Type="GroupLINQ" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="GroupLINQs">
    <Type Name="GroupLINQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReservationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="JoinedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HasBreakage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Group_GroupMember" Member="GroupMembers" ThisKey="Id" OtherKey="GroupId" Type="GroupMember" />
      <Association Name="Group_GroupItem" Member="GroupItems" ThisKey="Id" OtherKey="GroupId" Type="GroupItem" />
      <Association Name="Reservation_Group" Member="Reservation" ThisKey="ReservationId" OtherKey="Id" Type="Reservation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>